### ISSUE TITLE
Does not seem to work with region amounts above 20 or chunk amounts above 400

### ISSUE THREAD

**Issue by PatPeter** [DMBuce/mcexplore#1]
I am pregenerating a Pixelmon server using forge, and I was able to use this command perfectly fine to fix the generation of an existing world.

    pixelmon>"C:\Python27\python.exe" mcexplore.py -v -x 0 -z 0 -c "java -jar forge-1.8.9-11.15.1.1722-universal.jar nogui" -r 20 20

![Generated 20x20 regions](https://i.imgur.com/EHggDcU.jpg)

It generates from 5120, 5120 to -5120, -5120.

However, if I try to generate amounts above 20, such as 25, 26, or 27 to fill in the outcroppings at the bottom and on the right side, _it generates no new regions_. I refresh the world/region directory and no new regions are created at this distance out. Is there a server setting or something I can do to ensure that it's generating that far out?

**Comment by PatPeter** [comment]
Ah, it turns out that there was a worldborder set on this world, which makes no sense since I haven't used it since 2017 and if there was a worldborder set then, it wouldn't have allowed my users to generate beyond the world border...

**Comment by bigwoody2253** [comment]
Does removing the world border fix the issue and let mcexplore generate terrain past 5120?

**Comment by DMBuce** [comment]
Whoops, accidentally commented with an alt account.

Does removing the world border fix the issue and let mcexplore generate terrain past 5120?

**Comment by PatPeter** [comment]
Yes! Sorry, looks like I forgot to close this issue.
