### ISSUE TITLE
How to install & run this script on Debian?

### ISSUE THREAD

**Issue by SilkAndSlug** [DMBuce/mcexplore#3]
As title. 

I'd like to use your script to pre-generate a Vanilla world on my Debian server, to reduce lag during play. How would I do that?

**Comment by DMBuce** [comment]
I just added install and usage info to the readme. I only tested on Arch Linux but you should be able to use the instructions to pregenerate a world on any Linux distro, Debian or otherwise.

https://github.com/DMBuce/mcexplore#install

HTH
