### ISSUE TITLE
MCExplore crash on start on python 3.9

### ISSUE THREAD

**Issue by Matk3z** [DMBuce/mcexplore#7]
I'm trying to pre generate the world 63x63 chunk on a minecraft forge 1.18.1 server (forge version 39.0.59) on windows using the basic command provided by the documentation `python PATH_TO_MCEXPLORE\mcexplore.py -v -c "java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.1-39.0.44/win_args.txt nogui"` 
However when I run this command the script return an error
```Traceback (most recent call last):
  File "PATH_TO_MCEXPLORE\mcexplore.py", line 376, in <module>
  File "PATH_TO_MCEXPLORE\mcexplore.py", line 165, in main
    if basenames['levelbak'] in filenames:
TypeError: 'function' object is not subscriptable
```

So i've read throught the mcexplor.py script and I've found the issue.The basenames variable seems to be only defined in the getParser scope. I've made it work by doing a very bad workaround i.e. getting the definition of basenames out of the getParser function in main line 118 :
```
    parser = getParser()
    basenames = {
        'levelbak': "level.dat.explorebackup",
        'regionbak': "region.explorerename-overworld",
    }
```

It seems to work fine now but this is far from being an ideal fix. I don't know if this a bug that only happens on windows or if this  related to the newer versions of python.

**Comment by DMBuce** [comment]
The TypeError you're getting seems to indicate that there is a `basenames` function defined, which is strange. There is no such function in mcexplore AFAICT.

Regardless, it would be better to declare the `basenames` variable in the same scope it's used in, so the fix you proposed looks good to me. I'll push a commit with the fix shortly.
